#ifndef OBJENUM_H
#define OBJENUM_H

enum OBJ_ENUM { NOTHING, ICECUBE, PENGO, STONECUBE, ITEM_BLOCK_CREATION, ITEM_PLAYER_SPEED, ENEMY, PADDING };
enum CAMERA_TYPES { FIRST_PERSON, THIRD_PERSON, CEILING_VISION };

#endif // OBJENUM_H
